(() => {
  if (parent !== window) return;
  const native = (cmd,args) => window.__TAURI_INTERNALS__.invoke(cmd,args);
  const call = (cmd,args) => native(`plugin:molly-skills|${cmd}`,args);
  const checks = [];
  let stage = 'start', finished = false;
  const check = (ok,name) => { if(!ok) throw new Error(name); checks.push(name); };
  const rejects = async (fn,name) => {let rejected=false;try{await fn();}catch{rejected=true;}check(rejected,name);};
  const wait = async (fn,name) => {for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50));}throw new Error(name);};
  const report = result => {if(finished)return;finished=true;native('smoke_report',{result:{...result,stage,checks}});};
  const button = (scope,label) => [...scope.querySelectorAll('button')].find(b=>b.textContent.trim()===label);
  const run = async () => {try {
    const p=window.__skillPaths;
    await wait(()=>document.querySelector('[aria-label="Skill 管理器"]'),'Skill navigation');
    await rejects(()=>call('get_managed_skills'),'Module stays lazy before opening');
    check(!document.querySelector('[aria-label="MCP 市场"]'),'Independent MCP market removed');
    document.querySelector('[aria-label="Skill 管理器"]').click();
    await wait(()=>document.querySelector('.skills-frame')?.contentDocument.querySelector('.molly-skills-tabs'),'Skill frontend loads');
    const frame=document.querySelector('.skills-frame'), doc=frame.contentDocument;
    await call('initialize');
    check(Array.isArray(await call('get_managed_skills')),'Lazy initialization');
    check(!doc.body.textContent.includes('界面预览'),'Native module is not preview');
    check(getComputedStyle(doc.body).fontFamily===getComputedStyle(document.body).fontFamily,'Font follows console');
    await rejects(()=>call('app_exit'),'Standalone lifecycle IPC rejected');
    await rejects(()=>call('set_settings',{key:'theme',value:'dark'}),'Module cannot override host theme');
    const tools=await call('get_tool_status');
    check(tools.length>=54,'All built-in Agents are retained');
    check(tools.every(t=>t.skills_dir.startsWith(p.home)),'All Agent homes use isolated test directory');
    check(await call('get_settings',{key:'sync_mode'})==='copy','New Molly library defaults to copy deployment');
    stage='library';
    await call('install_local',{sourcePath:p.source,name:null});
    let skills=await call('get_managed_skills'), skill=skills.find(s=>s.name==='example-skill');
    check(!!skill,'Local folder imports into central library');
    check((await call('get_skill_document',{skillId:skill.id})).content.includes('local test'),'SKILL.md preview reads installed file');
    await call('set_skill_tags',{skillId:skill.id,tags:['test','开发']});
    check((await call('get_all_tags')).includes('开发'),'Unicode tags persist');
    await call('rename_tag',{oldName:'test',newName:'verified'});
    check((await call('get_all_tags')).includes('verified'),'Tag renaming works');
    const preset=await call('create_preset',{name:'Smoke preset',description:'temp',icon:null});
    await call('add_skill_to_preset',{skillId:skill.id,presetId:preset.id});
    check((await call('get_skills_for_preset',{presetId:preset.id})).length===1,'Preset membership persists');
    stage='deployment';
    await call('sync_skill_to_tool',{skillId:skill.id,tool:'codex'});
    skills=await call('get_managed_skills');
    check(skills.find(s=>s.id===skill.id).targets.some(t=>t.tool==='codex'),'Agent receives a managed deployment');
    await native('smoke_change_source');
    await call('reimport_local_skill',{skillId:skill.id,approvedRemovals:null});
    check((await call('get_skill_document',{skillId:skill.id})).content.includes('Updated test body'),'Local reimport updates content');
    const external=await call('get_global_local_skills',{agent:'codex'});
    check(external.some(s=>s.name==='unmanaged'),'Agent workspace discovers external skills');
    await call('install_local',{sourcePath:p.source,name:'unmanaged'});
    const conflict=(await call('get_managed_skills')).find(s=>s.name==='unmanaged');
    await rejects(()=>call('sync_skill_to_tool',{skillId:conflict.id,tool:'codex'}),'Unmanaged target cannot be overwritten');
    stage='projects';
    const project=await call('add_project',{path:p.project});
    await call('export_skill_to_project',{skillId:skill.id,projectId:project.id,agents:['codex']});
    check((await call('get_project_skills',{projectId:project.id})).some(s=>s.name==='example-skill'),'Project deployment works');
    const linked=await call('add_linked_workspace',{name:'Linked',path:p.linked,disabledPath:p.disabled});
    await call('export_skill_to_project',{skillId:skill.id,projectId:linked.id,agents:null});
    let rows=await call('get_project_skills',{projectId:linked.id}), row=rows[0];
    check(row?.name==='example-skill','Arbitrary skill-root workspace works');
    await call('toggle_project_skill',{projectId:linked.id,skillRelativePath:row.relative_path,agent:row.agent,enabled:false});
    check((await call('get_project_skills',{projectId:linked.id})).some(s=>!s.enabled),'Linked workspace can disable a skill');
    stage='backup';
    await call('backup_set_device_name',{name:'Molly smoke'});
    await call('git_backup_init');
    await rejects(()=>call('git_backup_set_remote',{url:p.remote}),'Public remote setup rejects arbitrary local paths');
    await native('smoke_prepare_remote');
    await call('set_skill_tags',{skillId:skill.id,tags:['verified','备份验证']});
    await call('git_backup_commit',{message:'isolated initial backup'});
    await call('git_backup_push');
    check((await call('git_backup_status')).is_repo,'Git backup initializes with isolated local remote');
    const snapshot=await call('git_backup_create_snapshot');
    const versions=await call('git_backup_list_versions',{limit:10});
    check(versions.length>0,'Backup snapshots can be listed');
    await call('set_skill_tags',{skillId:skill.id,tags:['changed-after-snapshot']});
    await call('git_backup_restore_version',{tag:versions[0].tag});
    check(!(await call('get_all_tags')).includes('changed-after-snapshot'),'Snapshot restoration restores metadata');
    stage='agent-cli';
    const bundled=await call('prepare_agent_control');
    await call('install_local',{sourcePath:bundled,name:null});
    const agentControl=(await call('get_managed_skills')).find(s=>s.name==='manage-molly-skills');
    check(!!agentControl,'Optional Agent-management skill installed into Molly library');
    const content=(await call('get_skill_document',{skillId:agentControl.id})).content;
    check(content.includes('--molly-skills-cli')&&!content.includes('.version')&&!content.includes('$HOME/.skills-manager'),'Agent-management instructions target Molly CLI');
    stage='ui-modal';
    doc.querySelector('a[href="#/organizer"]').click();
    await wait(()=>button(doc,'新建预设'),'Organizer navigation');
    button(doc,'新建预设').click();
    await wait(()=>doc.querySelector('[role="dialog"]'),'Create preset modal');
    await wait(()=>document.querySelector('.sidebar').inert,'Host navigation inert');
    check(!document.querySelector('.app-shell').inert&&!frame.closest('[inert]'),'Modal iframe remains interactive');
    button(doc.querySelector('[role="dialog"]'),'取消').click();
    await wait(()=>!document.querySelector('.sidebar').inert,'Closing restores navigation');
    document.documentElement.dataset.theme='dark';
    await wait(()=>doc.documentElement.dataset.theme==='dark','Theme propagation');
    check(getComputedStyle(doc.body).backgroundColor==='rgb(20, 26, 33)','Skill Manager uses shared dark background');
    stage='uninstall-and-isolation';
    await call('unsync_skill_from_tool',{skillId:skill.id,tool:'codex'});
    check(!(await call('get_managed_skills')).find(s=>s.id===skill.id).targets.some(t=>t.tool==='codex'),'Undeploy removes selected Agent only');
    await call('delete_managed_skill',{skillId:conflict.id});
    check(!(await call('get_managed_skills')).some(s=>s.id===conflict.id),'Delete removes central-library entry');
    await rejects(()=>call('set_central_repo_path',{path:p.home+'/.skills-manager'}),'Independent Skills Manager directory is protected');
    const original=await call('get_central_repo_path');
    await call('set_central_repo_path',{path:p.relocated});
    check(await call('get_central_repo_path')===original,'Relocation keeps current database and paths together until restart');
    check((await call('get_managed_skills')).some(s=>s.id===skill.id),'Library remains readable after scheduling relocation');
    report({ok:true});
  }catch(error){report({ok:false,error:typeof error==='object'?JSON.stringify(error,Object.getOwnPropertyNames(error)):String(error),text:document.body.innerText.slice(-1000),skillsText:document.querySelector('.skills-frame')?.contentDocument?.body.innerText.slice(-2000)});}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
